# This is a basic workflow to help you get started with Actions

name: Build Resume on Push

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Build the LaTex resume using a GitHub Action
      - name: LaTeX Action
        # You may pin to the exact commit or the version.
        uses: fudan-mse/latex-action@v0.0.1
        with:
          # The root LaTeX file to be compiled
          root_file: resume.tex
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.2
        with:
          name: resume.pdf
          path: resume.pdf

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
